-- Migration to add comments table for species entries
-- This allows users to add comments on species entries, ordered by recency

-- Create a table for comments on species
create table species_comments (
  id int generated by default as identity primary key,
  species_id int not null references species(id) on delete cascade,
  author uuid not null references profiles(id),
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table species_comments
  enable row level security;

-- Everyone can view comments
create policy "Comments are viewable by everyone." on species_comments
  for select using (true);

-- Users can insert their own comments
create policy "Users can insert their own comments." on species_comments
  for insert with check (auth.uid() = author);

-- Users can update their own comments
create policy "Users can update their own comments." on species_comments
  for update using (auth.uid() = author);

-- Users can delete their own comments
create policy "Users can delete their own comments." on species_comments
  for delete using (auth.uid() = author);

-- Create an index on species_id for faster queries
create index species_comments_species_id_idx on species_comments(species_id);

-- Create an index on created_at for faster ordering by recency
create index species_comments_created_at_idx on species_comments(created_at desc);
